version: "3.5"
services:
  php-fpm:
    environment:
      - WARPDRIVE_API=${WARPDRIVE_API}
      - WARPDRIVE_ACCESS_TOKEN=${WARPDRIVE_ACCESS_TOKEN}
      - WARPDRIVE_SYSTEM_NAME=${WARPDRIVE_SYSTEM_NAME}
    volumes:
      - ./.warden/wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./warpdrive-plugin:/var/www/html/wp-content/plugins/warpdrive
      - ./.warden/warpdrive/access.log:/var/www/wordpress/log/wordpress.access.log
      - ./.warden/warpdrive/error.log:/var/www/wordpress/log/wordpress.error.log
  wp-test:
    build:
      context: ./.warden/wordpress_test/
      args:
        - DB_HOST=${DB_HOST}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./warpdrive-plugin:/var/www/html/wp-content/plugins/warpdrive
volumes:
  data:
    driver: local
